services:
  postgres:
    image: postgres:15.5
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda